version: "3.8"

volumes:
  wpdb:
services:
  nginx:
    image: europe-north1-docker.pkg.dev/my-first-project-20220128/my-first-repository/nginx:1.21.5
    ports:
      - "80:8080"
    volumes:
      - ./../local/nginx/site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php
      - mysql
  php:
    image: europe-north1-docker.pkg.dev/my-first-project-20220128/my-first-repository/php:8.0.14
    environment:
      - WP_ENV=production
  mysql:
    image: mariadb:10.3.32
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    volumes:
      - wpdb:/var/lib/mysql
