FROM rig/nginx:1.21.5

COPY ./public/vendor /public/vendor
COPY ./public/wp /public/wp
COPY ./public/app /public/app
ADD ./public/index.php /public/index.php
ADD ./public/wp-config.php /public/wp-config.php
