FROM rig/php:8.0.14-mysqli-gd-intl

COPY ./public/vendor /public/vendor
COPY ./public/wp /public/wp
COPY ./public/app /public/app
ADD ./public/index.php /public/index.php
ADD ./public/wp-config.php /public/wp-config.php
