apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-uploads
spec:
  storageClassName: csi-gcs
  volumeName: wp-uploads
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 200Mi
